//
//  BeerDetailsPresenter.swift
//  
//
//  Created by Danilo Ramos on 04/10/18.
//  Copyright (c) 2018 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class BeerDetailsPresenter {

    // MARK: - Private properties -

    private unowned var _view: BeerDetailsViewInterface
    private var _interactor: BeerDetailsInteractorInterface
    private var _wireframe: BeerDetailsWireframeInterface
    
    private let _beer: Beer
    

    // MARK: - Lifecycle -

    init(wireframe: BeerDetailsWireframeInterface, view: BeerDetailsViewInterface, interactor: BeerDetailsInteractorInterface, beer: Beer) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
        _beer = beer
    }
}

// MARK: - Extensions -

extension BeerDetailsPresenter: BeerDetailsPresenterInterface {
    
    func viewDidLoad() {
        _view.setViewTitle(_beer.name)
        _view.setBeer(beer: _beer)
        
    }
 
}
