//
//  BeerDetailsInteractor.swift
//  
//
//  Created by Danilo Ramos on 04/10/18.
//  Copyright (c) 2018 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class BeerDetailsInteractor {
}

// MARK: - Extensions -

extension BeerDetailsInteractor: BeerDetailsInteractorInterface {
}
