//
//  BeerDetailsViewController.swift
//  
//
//  Created by Danilo Ramos on 04/10/18.
//  Copyright (c) 2018 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire
import AlamofireImage

final class BeerDetailsViewController: UIViewController {

    
    @IBOutlet weak var beerImage: UIImageView?
    @IBOutlet weak var id: UILabel?
    @IBOutlet weak var tagline: UILabel?
    @IBOutlet weak var beerDescription: UITextView?
    @IBOutlet weak var abv: UILabel?
    @IBOutlet weak var ibu: UILabel?
    @IBOutlet weak var ebc: UILabel?
    @IBOutlet weak var srm: UILabel?
    @IBOutlet weak var ph: UILabel?
    @IBOutlet weak var att_lvl: UILabel?
    @IBOutlet weak var brewer_tips: UITextView?
    @IBOutlet weak var contributed_by: UITextView?
    
    
    var beerDetails: Beer?

    
    // MARK: - Public properties -

    var presenter: BeerDetailsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        
        self.beerImage?.image = nil
        self.beerImage?.loadGif(name: "image-loader")
        Alamofire.request(beerDetails!.image_url ?? "https://www.brewdog.com/images/newshop/logo.png").responseImage { response in
            self.beerImage?.image = response.result.value
        }
        
        id?.text = String(beerDetails!.id ?? 0)
        tagline?.text = beerDetails!.tagline
        beerDescription?.text = beerDetails!.description
        abv?.text = String(beerDetails!.abv ?? 0)
        ibu?.text = String(beerDetails!.ibu ?? 0)
        ph?.text = String(beerDetails!.ph ?? 0)
        att_lvl?.text = String(beerDetails!.attenuation_level ?? 0)
        ebc?.text = String(beerDetails!.ebc ?? 0)
        srm?.text = String(beerDetails!.srm ?? 0)
        brewer_tips?.text = beerDetails!.brewer_tips
        contributed_by?.text = beerDetails!.contributed_by
        
    }
}

// MARK: - Extensions -

extension BeerDetailsViewController: BeerDetailsViewInterface {
    func setViewTitle(_ title: String?) {
        navigationItem.title = title
    }
    
    func setBeer(beer: Beer?) {
        beerDetails = beer
    }
}
