//
//  MainListViewController.swift
//  BeerCatalog
//
//  Created by Danilo Ramos on 01/10/18.
//  Copyright (c) 2018 Danilo Ramos. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

final class MainListViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
        
    var list: [Beer] = []
    @IBOutlet weak var tableView: UITableView!
    
        public func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int{
            return(list.count)
        }
        
        public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
            let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as! BeerCell
            let beer = list[indexPath.row]
            cell.beerName?.text = beer.name
            cell.tagLine?.text = beer.tagline
            
            return(cell)
        }
    

    // MARK: - Public properties -

    var presenter: MainListPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }
	
}

// MARK: - Extensions -

extension MainListViewController: MainListViewInterface {
    func showErrorMessage(message: String) {
        
    }
    
    func setItems(beerList: [Beer]) {
        list = beerList
        tableView.reloadData()
    }
    
}
