//
//  MainListWireframe.swift
//  BeerCatalog
//
//  Created by Danilo Ramos on 01/10/18.
//  Copyright (c) 2018 Danilo Ramos. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainListWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "MainList", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: MainListViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = MainListInteractor()
        let presenter = MainListPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MainListWireframe: MainListWireframeInterface {

    func navigate(to option: MainListNavigationOption) {
    }
}
