//
//  MainListPresenter.swift
//  BeerCatalog
//
//  Created by Danilo Ramos on 01/10/18.
//  Copyright (c) 2018 Danilo Ramos. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainListPresenter {

    // MARK: - Private properties -

    private unowned var _view: MainListViewInterface
    private var _interactor: MainListInteractorInterface
    private var _wireframe: MainListWireframeInterface
    
    var filter = BeerFilter(index: 1, length: 30)
    var beerList = [] as [Beer]

    // MARK: - Lifecycle -

    init(wireframe: MainListWireframeInterface, view: MainListViewInterface, interactor: MainListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension MainListPresenter: MainListPresenterInterface {

    func didSelectItem(beer: Beer) {
        _wireframe.navigate(to: .details(beer))
    }
    
    func addIndexToFilter() {
        filter.index! += 1
        if(filter.length! <= beerList.count) {
           loadBeers()
        }
    }
    
    func loadBeers() {
        _interactor.getBeerList(filter: filter) { (beerList, statusCode, errorMessage) in
            if(beerList != nil){
                self.beerList = beerList!
                self._view.setItems(beerList: beerList!)
            } else {
                //self._view.showErrorMessage(message: errorMessage!)
            }
        }
    }
    
    func viewDidLoad() {
        loadBeers()
        _view.setViewTitle()
    }
}
