//
//  MainListPresenter.swift
//  BeerCatalog
//
//  Created by Danilo Ramos on 01/10/18.
//  Copyright (c) 2018 Danilo Ramos. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainListPresenter {

    // MARK: - Private properties -

    private unowned var _view: MainListViewInterface
    private var _interactor: MainListInteractorInterface
    private var _wireframe: MainListWireframeInterface

    // MARK: - Lifecycle -

    init(wireframe: MainListWireframeInterface, view: MainListViewInterface, interactor: MainListInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension MainListPresenter: MainListPresenterInterface {
    
    func viewDidLoad() {
        _interactor.getBeerList { (beerList, statusCode, errorMessage) in
            if(beerList != nil){
                print(beerList?[0].name)
                self._view.setItems(beerList: beerList!)
            } else {
                //self._view.showErrorMessage(message: errorMessage!)
            }
        }
    }
}
