//
//  MainListInterfaces.swift
//  BeerCatalog
//
//  Created by Danilo Ramos on 01/10/18.
//  Copyright (c) 2018 Danilo Ramos. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum MainListNavigationOption {
    case details(Beer)
}

protocol MainListWireframeInterface: WireframeInterface {
    func navigate(to option: MainListNavigationOption)
}

protocol MainListViewInterface: ViewInterface {
    
    func showErrorMessage(message: String)
    
    func setItems(beerList: [Beer])
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)
    
    func setViewTitle()
}

protocol MainListPresenterInterface: PresenterInterface {
    
    func didSelectItem(beer: Beer)
}

protocol MainListInteractorInterface: InteractorInterface {
    
    func getBeerList(completion: @escaping ([Beer]?, Int, String?) -> ())
}
